import type { Metadata } from 'next'
import {
  Inter,
  Istok_Web,
  Lalezar,
  Lancelot,
  Lateef,
  Montserrat,
  Raleway,
  Ramaraja,
  Urbanist,
  Vesper_Libre,
} from 'next/font/google'
import './globals.css'
import { QueryProvider } from './providers/queryClientProvider'
import { ReduxProvider } from './providers/reduxProvider'

const urbanist = Urbanist({
  variable: '--font-urbanist',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})
const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})
const vesper = Vesper_Libre({
  variable: '--font-vesper',
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
})
const ramaraja = Ramaraja({
  variable: '--font-ramaraja',
  subsets: ['latin'],
  weight: ['400'],
})
const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})
const lateef = Lateef({
  variable: '--font-lateef',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
})
const istokWeb = Istok_Web({
  variable: '--font-istokWeb',
  subsets: ['latin'],
  weight: ['400', '700'],
})
const lalezar = Lalezar({
  variable: '--font-lalezar',
  subsets: ['latin'],
  weight: ['400'],
})
const lancelot = Lancelot({
  variable: '--font-lancelot',
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Portgig',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.JSX.Element | React.JSX.Element[]
}>) {
  return (
    <html lang='en'>
      <body
        className={`${urbanist.variable} ${inter.variable} ${raleway.variable} ${vesper.variable} ${ramaraja.variable} ${montserrat.variable} ${lateef.variable} ${istokWeb.variable} ${lalezar.variable} ${lancelot.variable} font-raleway`}
      >
        {' '}
        <ReduxProvider>
          <QueryProvider>{children}</QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
